### ISSUE TITLE
Move to xDai

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-orga#33]
- [ ] Transfer ETH to xDai network (via https://dai-bridge.poa.network)
- [ ] Optional: Upgrade to Gnosis Safe contracts v.1.1.1 (https://github.com/CirclesUBI/circles-contracts/issues/82)
- [ ] Optional: Upgrade Relayer (https://github.com/CirclesUBI/safe-relay-service/issues/14)
- [ ] Register Circles subgraph on The Graph xDai node
- [ ] Deploy Circles Contracts on xDai
- [ ] Optional: Set up backups via borg (https://github.com/CirclesUBI/circles-docker/issues/5)
- [ ] Setting up new Linux server for Circles infrastructure
- [ ] :sunflower:
